//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarLight_Ticket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_Save
    {
        public int SID_save { get; set; }
        public Nullable<int> SportID { get; set; }
        public string UserName { get; set; }
        public string SportTheatre { get; set; }
        public string Sportname { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Toatal { get; set; }
    
        public virtual Sport Sport { get; set; }
    }
}
