//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarLight_Ticket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StarLightTicketsEntities : DbContext
    {
        public StarLightTicketsEntities()
            : base("name=StarLightTicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<Cinema_fix> Cinema_fix { get; set; }
        public virtual DbSet<Cinema_Save> Cinema_Save { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Sport_fix> Sport_fix { get; set; }
        public virtual DbSet<Sport_Save> Sport_Save { get; set; }
        public virtual DbSet<Theatre> Theatres { get; set; }
        public virtual DbSet<Theatre_fix> Theatre_fix { get; set; }
        public virtual DbSet<Theatre_Save> Theatre_Save { get; set; }
    }
}
